### ISSUE TITLE
1.12.2 fails to build w/ OpenSSL-1.1: libgadu.so: undefined reference to `SSLv3_client_method

### ISSUE THREAD

**Issue by a17r** [wojtekka/libgadu#29]
See also: [build.log](https://github.com/wojtekka/libgadu/files/3125473/build.log)

**Comment by wojtekka** [comment]
Looks like not many people build the library with OpenSSL. If it's possible for you to build from  [bugfix/sslv3_method_client-deprecated](https://github.com/wojtekka/libgadu/tree/bugfix/sslv3_method_client-deprecated) branch before I merge pull request #30, I'd appreciate it. If not, we'll go on anyway and see what happens.

**Comment by a17r** [comment]
Thanks for your reply, builds and links fine against openssl-1.1.0j!

**Comment by marcin-github** [comment]
openssl-1.1.x now is in stable Gentoo, today I hit this issue.
Branch `bugfix/sslv3_method_client-deprecated` compiles fine with  openssl-1.1.1d-r2.
